name: security_police_app
description: 'Security Police RD App, control de seguridad y registro de activedades de la policía.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  audioplayers: ^6.0.0
  permission_handler: ^11.0.0
  get_it: ^7.7.0
  intl: ^0.19.0
  flutter_sound: ^9.8.1
  file_picker: ^5.0.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons:

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/police_logo.png'
  adaptive_icon_background: 'assets/images/police_logo.png'

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/avatar.jpg
